basePath: /
definitions:
  handlers.UpdateTaskStatusRequest:
    properties:
      status:
        type: string
    type: object
  taskdomain.Task:
    properties:
      completed:
        type: boolean
      id:
        type: string
      title:
        type: string
    type: object
host: todolistgo-57814d96dd24.herokuapp.com
info:
  contact: {}
  description: API feita em Golang para gerenciamento de tarefas
  title: API TodoList GO
  version: "1.0"
paths:
  /tasks:
    get:
      consumes:
      - application/json
      description: Retorna todas as tarefas cadastradas
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/taskdomain.Task'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista todas as tarefas
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Adiciona uma nova tarefa à lista
      parameters:
      - description: Dados da Tarefa
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/taskdomain.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/taskdomain.Task'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cria uma nova tarefa
      tags:
      - tasks
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Deleta uma tarefa existente
      parameters:
      - description: ID da Tarefa
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Deleta uma tarefa
      tags:
      - tasks
  /tasks/attStatus/{id}:
    put:
      consumes:
      - application/json
      description: Atualiza o status de uma tarefa existente
      parameters:
      - description: ID da Tarefa
        in: path
        name: id
        required: true
        type: string
      - description: Status da Tarefa
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.UpdateTaskStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Atualiza o status de uma tarefa
      tags:
      - tasks
schemes:
- https
swagger: "2.0"
